language: python
python:
    - pypy
env:
    - PORT_VER="2.3.1"
before_install:
    - sudo apt-get -qq update
    - pip install lxml
before_script:
    - mkdir travis-overlay
    - mv !(travis-overlay) travis-overlay/
    - mv .git travis-overlay/
    - wget "https://raw.githubusercontent.com/mrueg/repoman-travis/master/spinner.sh"
    - wget "https://github.com/gentoo/portage/archive/portage-${PORT_VER}.tar.gz" -O portage-${PORT_VER}.tar.gz
    - wget "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" -O portage-tree.tar.gz
    - sudo chmod a+rwX /etc/passwd /etc/group /etc /usr spinner.sh
    - chmod a+rwx spinner.sh
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - mkdir -p /etc/portage /usr/portage/distfiles
    - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /usr/portage/distfiles/metadata.dtd
    - tar xzf portage-${PORT_VER}.tar.gz && mv portage-portage-${PORT_VER} portage-${PORT_VER}
    - tar xzf portage-tree.tar.gz -C /usr/portage --strip-components=1
    - cp portage-${PORT_VER}/cnf/repos.conf /etc/portage/
    - ln -s /usr/portage/profiles/base/ /etc/portage/make.profile
    - cd travis-overlay
script:
- ./../spinner.sh "python ../portage-${PORT_VER}/repoman/bin/repoman full"
